/// Flutter icons LeaveApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LeaveApp
///      fonts:
///       - asset: fonts/LeaveApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LeaveApp {
  LeaveApp._();

  static const _kFontFam = 'LeaveApp';
  static const String? _kFontPkg = null;

  static const IconData hamburger_menu = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_bell = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reason = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calender = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leave_type = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
